language: java
before_install:
- mkdir /tmp/bin
- export PATH=$PATH:/tmp/bin
install:
- curl --location 'https://www.ortussolutions.com/parent/download/commandbox/type/bin' -o /tmp/box.zip
- unzip /tmp/box.zip -d /tmp/bin
- /tmp/bin/box install
script:
- ./test.sh
- ant -f build/build.xml -Dsource=remote -Dwork.dir=$HOME/work -Dbuild.dir=$TRAVIS_BUILD_DIR -Dplatform=$PLATFORM -Dbranch=$TRAVIS_BRANCH -Dtag=$TRAVIS_TAG $TARGET

deploy:
  provider: s3
  access_key_id: AKIAJ3PTU73IHOOZV3LQ
  secret_access_key:
    secure: WMBNULr8RwOLrcIpOkjCgKjo4492ITvkdNAnZRLKhxRqrcRGpF/KwlCGm+Lhmdo4gc0Kv+6Cuou/7dx2eH/0Updg+qDgpbB5akmjxcXCfYTvc6v5n73FZ/sJBjnVpYSBSovn6OcbLcJF+Smqld0czBDtqobnBuwXvyUa/egA+A4=
  bucket: downloads.presidecms.com
  local-dir: build/artifacts
  upload-dir: sticker
  skip_cleanup: true
  on:
    repo: pixl8/sticker
    branch: stable